# Generated by Django 4.0.5 on 2022-08-19 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('point_register', '0002_userpoint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Type',
        ),
    ]
